Remove unused include from SonyGamepadProxy.h
With this include, we're getting

C:\UnrealEngine\Engine\Source\Runtime\Core\Public\Windows\AllowWindowsPlatformTypes.h(15,22): fatal error C1189: #error:  Nesting AllowWindowsPlatformTypes.h is not allowed!
	#error Nesting AllowWindowsPlatformTypes.h is not allowed!
	                    ^